// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type DoTodo struct {
	ID string `json:"id"`
}

type NewTodo struct {
	Text string `json:"text"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Session struct {
	UserID string `json:"user_id"`
	Token  string `json:"token"`
}

type Todo struct {
	ID        string          `json:"id"`
	Content   string          `json:"content"`
	Completed bool            `json:"completed"`
	Deleted   bool            `json:"deleted"`
	Author    *UserNoPassword `json:"author"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	IsVerify bool   `json:"isVerify"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserNoPassword struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	IsVerify bool   `json:"isVerify"`
	Email    string `json:"email"`
}
